// Code generated by protoc-gen-go. DO NOT EDIT.
// source: localcommon.proto

package go_kafka

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// -识别类型，1为车辆识别（机动车，非机动车，行人），2为人脸识别，3为先进行车辆识别，然后对车辆识别得到的对象进行人脸识别
type RecognizeType int32

const (
	RecognizeType_REC_TYPE_INVALID RecognizeType = 0
	RecognizeType_REC_TYPE_VEHICLE RecognizeType = 1
	RecognizeType_REC_TYPE_FACE    RecognizeType = 2
	RecognizeType_REC_TYPE_ALL     RecognizeType = 3
)

var RecognizeType_name = map[int32]string{
	0: "REC_TYPE_INVALID",
	1: "REC_TYPE_VEHICLE",
	2: "REC_TYPE_FACE",
	3: "REC_TYPE_ALL",
}
var RecognizeType_value = map[string]int32{
	"REC_TYPE_INVALID": 0,
	"REC_TYPE_VEHICLE": 1,
	"REC_TYPE_FACE":    2,
	"REC_TYPE_ALL":     3,
}

func (x RecognizeType) String() string {
	return proto.EnumName(RecognizeType_name, int32(x))
}
func (RecognizeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_localcommon_956cf1e60edfa725, []int{0}
}

type RankType int32

const (
	RankType_RANK_TYPE_DEFAULT RankType = 0
	RankType_RANK_TYPE_VEHICLE RankType = 1
	RankType_RANK_TYPE_FACE    RankType = 2
)

var RankType_name = map[int32]string{
	0: "RANK_TYPE_DEFAULT",
	1: "RANK_TYPE_VEHICLE",
	2: "RANK_TYPE_FACE",
}
var RankType_value = map[string]int32{
	"RANK_TYPE_DEFAULT": 0,
	"RANK_TYPE_VEHICLE": 1,
	"RANK_TYPE_FACE":    2,
}

func (x RankType) String() string {
	return proto.EnumName(RankType_name, int32(x))
}
func (RankType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_localcommon_956cf1e60edfa725, []int{1}
}

// -识别的功能代码
type RecognizeFunctions int32

const (
	RecognizeFunctions_RECFUNC_INVALID                         RecognizeFunctions = 0
	RecognizeFunctions_RECFUNC_VEHICLE_DETECT                  RecognizeFunctions = 100
	RecognizeFunctions_RECFUNC_MOTOR_STYLE                     RecognizeFunctions = 101
	RecognizeFunctions_RECFUNC_MOTOR_COLOR                     RecognizeFunctions = 102
	RecognizeFunctions_RECFUNC_MOTOR_MARKER                    RecognizeFunctions = 103
	RecognizeFunctions_RECFUNC_MOTOR_PLATE                     RecognizeFunctions = 104
	RecognizeFunctions_RECFUNC_MOTOR_FEATURE                   RecognizeFunctions = 105
	RecognizeFunctions_RECFUNC_MOTOR_DRIVER_BELT               RecognizeFunctions = 106
	RecognizeFunctions_RECFUNC_MOTOR_DRIVER_PHONE              RecognizeFunctions = 107
	RecognizeFunctions_RECFUNC_MOTOR_CODRIVER_BELT             RecognizeFunctions = 108
	RecognizeFunctions_RECFUNC_MOTOR_DANGEROUS_ARTICLES_DETECT RecognizeFunctions = 109
	RecognizeFunctions_RECFUNC_MOTOR_HEAVY_POLLUTION_DETECT    RecognizeFunctions = 110
	RecognizeFunctions_RECFUNC_MOTOR_MUCK_DETECT               RecognizeFunctions = 111
	RecognizeFunctions_RECFUNC_MOTOR_FACECOVER_DETECT          RecognizeFunctions = 112
	RecognizeFunctions_RECFUNC_FACE_DETECT                     RecognizeFunctions = 200
	RecognizeFunctions_RECFUNC_FACE_ALIGNMENT                  RecognizeFunctions = 201
	RecognizeFunctions_RECFUNC_FACE_QUALITY_LV1                RecognizeFunctions = 202
	RecognizeFunctions_RECFUNC_FACE_QUALITY_LV2                RecognizeFunctions = 203
	RecognizeFunctions_RECFUNC_FACE_FEATURE                    RecognizeFunctions = 204
	RecognizeFunctions_RECFUNC_FACE_ATTRIBUTE                  RecognizeFunctions = 205
	RecognizeFunctions_RECFUNC_PEDESTRIAN_ATTRIBUTE            RecognizeFunctions = 300
	RecognizeFunctions_RECFUNC_PEDESTRIAN_FEATURE              RecognizeFunctions = 301
	RecognizeFunctions_RECFUNC_NON_MOTOR_ATTRIBUTE             RecognizeFunctions = 400
	RecognizeFunctions_RECFUNC_NON_MOTOR_FEATURE               RecognizeFunctions = 401
	RecognizeFunctions_RECFUNC_NON_MOTOR_LICENSE_PLATE         RecognizeFunctions = 402
)

var RecognizeFunctions_name = map[int32]string{
	0:   "RECFUNC_INVALID",
	100: "RECFUNC_VEHICLE_DETECT",
	101: "RECFUNC_MOTOR_STYLE",
	102: "RECFUNC_MOTOR_COLOR",
	103: "RECFUNC_MOTOR_MARKER",
	104: "RECFUNC_MOTOR_PLATE",
	105: "RECFUNC_MOTOR_FEATURE",
	106: "RECFUNC_MOTOR_DRIVER_BELT",
	107: "RECFUNC_MOTOR_DRIVER_PHONE",
	108: "RECFUNC_MOTOR_CODRIVER_BELT",
	109: "RECFUNC_MOTOR_DANGEROUS_ARTICLES_DETECT",
	110: "RECFUNC_MOTOR_HEAVY_POLLUTION_DETECT",
	111: "RECFUNC_MOTOR_MUCK_DETECT",
	112: "RECFUNC_MOTOR_FACECOVER_DETECT",
	200: "RECFUNC_FACE_DETECT",
	201: "RECFUNC_FACE_ALIGNMENT",
	202: "RECFUNC_FACE_QUALITY_LV1",
	203: "RECFUNC_FACE_QUALITY_LV2",
	204: "RECFUNC_FACE_FEATURE",
	205: "RECFUNC_FACE_ATTRIBUTE",
	300: "RECFUNC_PEDESTRIAN_ATTRIBUTE",
	301: "RECFUNC_PEDESTRIAN_FEATURE",
	400: "RECFUNC_NON_MOTOR_ATTRIBUTE",
	401: "RECFUNC_NON_MOTOR_FEATURE",
	402: "RECFUNC_NON_MOTOR_LICENSE_PLATE",
}
var RecognizeFunctions_value = map[string]int32{
	"RECFUNC_INVALID":                         0,
	"RECFUNC_VEHICLE_DETECT":                  100,
	"RECFUNC_MOTOR_STYLE":                     101,
	"RECFUNC_MOTOR_COLOR":                     102,
	"RECFUNC_MOTOR_MARKER":                    103,
	"RECFUNC_MOTOR_PLATE":                     104,
	"RECFUNC_MOTOR_FEATURE":                   105,
	"RECFUNC_MOTOR_DRIVER_BELT":               106,
	"RECFUNC_MOTOR_DRIVER_PHONE":              107,
	"RECFUNC_MOTOR_CODRIVER_BELT":             108,
	"RECFUNC_MOTOR_DANGEROUS_ARTICLES_DETECT": 109,
	"RECFUNC_MOTOR_HEAVY_POLLUTION_DETECT":    110,
	"RECFUNC_MOTOR_MUCK_DETECT":               111,
	"RECFUNC_MOTOR_FACECOVER_DETECT":          112,
	"RECFUNC_FACE_DETECT":                     200,
	"RECFUNC_FACE_ALIGNMENT":                  201,
	"RECFUNC_FACE_QUALITY_LV1":                202,
	"RECFUNC_FACE_QUALITY_LV2":                203,
	"RECFUNC_FACE_FEATURE":                    204,
	"RECFUNC_FACE_ATTRIBUTE":                  205,
	"RECFUNC_PEDESTRIAN_ATTRIBUTE":            300,
	"RECFUNC_PEDESTRIAN_FEATURE":              301,
	"RECFUNC_NON_MOTOR_ATTRIBUTE":             400,
	"RECFUNC_NON_MOTOR_FEATURE":               401,
	"RECFUNC_NON_MOTOR_LICENSE_PLATE":         402,
}

func (x RecognizeFunctions) String() string {
	return proto.EnumName(RecognizeFunctions_name, int32(x))
}
func (RecognizeFunctions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_localcommon_956cf1e60edfa725, []int{2}
}

type Time struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=Seconds,proto3" json:"Seconds,omitempty"`
	NanoSecs             int64    `protobuf:"varint,2,opt,name=NanoSecs,proto3" json:"NanoSecs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_localcommon_956cf1e60edfa725, []int{0}
}
func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (dst *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(dst, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Time) GetNanoSecs() int64 {
	if m != nil {
		return m.NanoSecs
	}
	return 0
}

type MatrixError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatrixError) Reset()         { *m = MatrixError{} }
func (m *MatrixError) String() string { return proto.CompactTextString(m) }
func (*MatrixError) ProtoMessage()    {}
func (*MatrixError) Descriptor() ([]byte, []int) {
	return fileDescriptor_localcommon_956cf1e60edfa725, []int{1}
}
func (m *MatrixError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatrixError.Unmarshal(m, b)
}
func (m *MatrixError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatrixError.Marshal(b, m, deterministic)
}
func (dst *MatrixError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatrixError.Merge(dst, src)
}
func (m *MatrixError) XXX_Size() int {
	return xxx_messageInfo_MatrixError.Size(m)
}
func (m *MatrixError) XXX_DiscardUnknown() {
	xxx_messageInfo_MatrixError.DiscardUnknown(m)
}

var xxx_messageInfo_MatrixError proto.InternalMessageInfo

func (m *MatrixError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MatrixError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Time)(nil), "Time")
	proto.RegisterType((*MatrixError)(nil), "MatrixError")
	proto.RegisterEnum("RecognizeType", RecognizeType_name, RecognizeType_value)
	proto.RegisterEnum("RankType", RankType_name, RankType_value)
	proto.RegisterEnum("RecognizeFunctions", RecognizeFunctions_name, RecognizeFunctions_value)
}

func init() { proto.RegisterFile("localcommon.proto", fileDescriptor_localcommon_956cf1e60edfa725) }

var fileDescriptor_localcommon_956cf1e60edfa725 = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xdf, 0x6e, 0xd3, 0x4c,
	0x10, 0xc5, 0x9b, 0xa4, 0x5f, 0xbf, 0x32, 0x50, 0xd8, 0x4e, 0x5b, 0x48, 0x5b, 0xda, 0xb4, 0x55,
	0x25, 0xaa, 0x22, 0x45, 0x02, 0x2e, 0xe1, 0x66, 0xeb, 0x4c, 0x5a, 0xab, 0x1b, 0x3b, 0x6c, 0xd6,
	0x91, 0x72, 0x65, 0x8c, 0x6d, 0x42, 0x68, 0xe2, 0x8d, 0x92, 0x20, 0x01, 0x4f, 0x01, 0x5c, 0xf1,
	0x10, 0xf0, 0x1e, 0xfc, 0x7d, 0x27, 0x14, 0x37, 0x8e, 0xe3, 0xa6, 0xe2, 0x6e, 0xe7, 0xfc, 0xce,
	0x9e, 0x9d, 0xcc, 0x44, 0x86, 0xd5, 0xae, 0xf6, 0xbd, 0xae, 0xaf, 0x7b, 0x3d, 0x1d, 0x95, 0xfb,
	0x03, 0x3d, 0xd2, 0x07, 0xcf, 0x60, 0x51, 0x75, 0x7a, 0x21, 0x16, 0xe1, 0xff, 0x46, 0xe8, 0xeb,
	0x28, 0x18, 0x16, 0x73, 0x7b, 0xb9, 0xa3, 0x82, 0x4c, 0x4a, 0xdc, 0x82, 0x65, 0xcb, 0x8b, 0x74,
	0x23, 0xf4, 0x87, 0xc5, 0x7c, 0x8c, 0xa6, 0xf5, 0xc1, 0x53, 0xb8, 0x59, 0xf3, 0x46, 0x83, 0xce,
	0x3b, 0x1a, 0x0c, 0xf4, 0x00, 0x11, 0x16, 0x0d, 0x1d, 0x84, 0x71, 0xc2, 0x7f, 0x32, 0x3e, 0x8f,
	0x83, 0x6b, 0xe1, 0x70, 0xe8, 0xb5, 0xc3, 0xf8, 0xf6, 0x0d, 0x99, 0x94, 0xc7, 0x2f, 0x60, 0x45,
	0x86, 0xbe, 0x6e, 0x47, 0x9d, 0x0f, 0xa1, 0x7a, 0xdf, 0x0f, 0x71, 0x1d, 0x98, 0x24, 0xc3, 0x55,
	0xad, 0x3a, 0xb9, 0xa6, 0xd5, 0xe4, 0xc2, 0xac, 0xb0, 0x85, 0x8c, 0xda, 0xa4, 0x33, 0xd3, 0x10,
	0xc4, 0x72, 0xb8, 0x0a, 0x2b, 0x53, 0xb5, 0xca, 0x0d, 0x62, 0x79, 0x64, 0x70, 0x6b, 0x2a, 0x71,
	0x21, 0x58, 0xe1, 0x58, 0xc0, 0xb2, 0xf4, 0xa2, 0x8b, 0x38, 0x7c, 0x03, 0x56, 0x25, 0xb7, 0xce,
	0x2f, 0x71, 0x85, 0xaa, 0xdc, 0x11, 0x8a, 0x2d, 0x64, 0xe5, 0x34, 0x1e, 0xe1, 0x76, 0x2a, 0x5f,
	0xe6, 0x1f, 0x7f, 0x59, 0x02, 0x9c, 0x36, 0x5c, 0x7d, 0x1b, 0xf9, 0xa3, 0x8e, 0x8e, 0x86, 0xb8,
	0x06, 0x77, 0x24, 0x19, 0x55, 0xc7, 0x32, 0x66, 0x9a, 0xde, 0x82, 0xbb, 0x89, 0x38, 0x09, 0x75,
	0x2b, 0xa4, 0xc8, 0x50, 0x2c, 0xc0, 0x7b, 0xb0, 0x96, 0xb0, 0x9a, 0xad, 0x6c, 0xe9, 0x36, 0x54,
	0x4b, 0x10, 0x0b, 0xe7, 0x81, 0x61, 0x0b, 0x5b, 0xb2, 0x57, 0x58, 0x84, 0xf5, 0x2c, 0xa8, 0x71,
	0x79, 0x4e, 0x92, 0xb5, 0xe7, 0xaf, 0xd4, 0x05, 0x57, 0xc4, 0x5e, 0xe3, 0x26, 0x6c, 0x64, 0x41,
	0x95, 0xb8, 0x72, 0x24, 0xb1, 0x0e, 0xee, 0xc0, 0x66, 0x16, 0x55, 0xa4, 0xd9, 0x24, 0xe9, 0x9e,
	0x90, 0x50, 0xec, 0x0d, 0xee, 0xc2, 0xd6, 0xb5, 0xb8, 0x7e, 0x66, 0x5b, 0xc4, 0x2e, 0xb0, 0x04,
	0xdb, 0x57, 0xbb, 0x9c, 0x0d, 0xe8, 0xe2, 0x43, 0x78, 0x70, 0x25, 0x80, 0x5b, 0xa7, 0x24, 0x6d,
	0xa7, 0xe1, 0x72, 0xa9, 0xc6, 0xb3, 0x68, 0x24, 0xc3, 0xe8, 0xe1, 0x11, 0x1c, 0x66, 0xcd, 0x67,
	0xc4, 0x9b, 0x2d, 0xb7, 0x6e, 0x0b, 0xe1, 0x28, 0xd3, 0xb6, 0x12, 0x67, 0x34, 0xdf, 0x76, 0xcd,
	0x31, 0xce, 0x13, 0xac, 0xf1, 0x00, 0x76, 0xaf, 0xfc, 0x60, 0x6e, 0x90, 0x61, 0x8f, 0xfb, 0x9a,
	0x78, 0xfa, 0x58, 0x4c, 0xa7, 0x35, 0xa6, 0x09, 0xf8, 0x9e, 0xc3, 0xed, 0x74, 0x5f, 0x31, 0xe1,
	0xc2, 0x3c, 0xb5, 0x6a, 0x64, 0x29, 0xf6, 0x23, 0x87, 0x3b, 0x50, 0xcc, 0xc0, 0xe7, 0x0e, 0x17,
	0xa6, 0x6a, 0xb9, 0xa2, 0xf9, 0x88, 0xfd, 0xfc, 0x17, 0x7e, 0xcc, 0x7e, 0xe5, 0x70, 0x33, 0x5d,
	0x5e, 0x8c, 0x93, 0x45, 0xfc, 0xbe, 0xe6, 0x55, 0xa5, 0xa4, 0x79, 0xe2, 0x28, 0x62, 0x7f, 0x72,
	0xb8, 0x0f, 0xf7, 0x13, 0x58, 0xa7, 0x0a, 0x35, 0x94, 0x34, 0xb9, 0x35, 0x63, 0xf9, 0x9a, 0xc7,
	0x52, 0xba, 0xaa, 0x19, 0x4b, 0xf2, 0xc0, 0xb7, 0x3c, 0xee, 0xa5, 0xbb, 0xb2, 0x6c, 0x6b, 0x32,
	0x98, 0x34, 0xe2, 0x63, 0x01, 0x77, 0xd3, 0xa9, 0xa6, 0x8e, 0x24, 0xe1, 0x53, 0x01, 0x0f, 0xa1,
	0x34, 0xcf, 0x85, 0x69, 0x90, 0xd5, 0xa0, 0xc9, 0x9f, 0xed, 0x73, 0xe1, 0x64, 0x1f, 0x4a, 0xbe,
	0xee, 0x95, 0x83, 0x30, 0xec, 0xb7, 0xbb, 0x9d, 0x68, 0x14, 0x9f, 0x02, 0x6f, 0xe4, 0x95, 0x83,
	0x76, 0xb9, 0xa7, 0x83, 0xb0, 0xfb, 0x72, 0x29, 0xfe, 0xde, 0x3c, 0xf9, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0xd0, 0x77, 0xdf, 0x24, 0x84, 0x04, 0x00, 0x00,
}
